name: Release

on:
  workflow_call:

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: release
  cancel-in-progress: false

jobs:
  release:
    runs-on:
      - self-hosted
      - linux

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: googleapis/release-please-action@v4
        with:
          release-type: simple
          token: ${{ secrets.GH_TOKEN }}
